module SkelGrammarB where

-- Haskell module generated by the BNF converter

import AbsGrammarB
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transB :: B -> Result
transB x = case x of
  BAdd b1 b2 -> failure x
  BMul b1 b2 -> failure x
  BNum integer -> failure x

