

module AbsMLang where

-- Haskell module generated by the BNF converter




data MPro = Program Com
  deriving (Eq, Ord, Show, Read)

data Com = Command Ins | IString String Com
  deriving (Eq, Ord, Show, Read)

data Ins = Instruction
  deriving (Eq, Ord, Show, Read)

