

module AbsLispKit where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data SExp
    = AtomI Integer
    | AtomV Ident
    | Cons SExp SExp
    | Brakets
    | Lst [SExp]
  deriving (Eq, Ord, Show, Read)

