module SkelLispKit where

-- Haskell module generated by the BNF converter

import AbsLispKit
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transSExp :: SExp -> Result
transSExp x = case x of
  AtomI integer -> failure x
  AtomV ident -> failure x
  Cons sexp1 sexp2 -> failure x
  Brakets -> failure x
  Lst sexps -> failure x

